export const movies = [
  {
    "id": 0,
    "title": "Fast X",
    "description": "Dom Toretto dan keluarganya menjadi sasaran putra gembong narkoba Hernan Reyes yang pendendam.",
    "release_date": "2023-05-17",
    "poster": "https://image.tmdb.org/t/p/w500/fiVW06jE7z9YnO4trhaMEdclSiC.jpg",
    "movie_format": "2D",
    "duration": 120,
    "director": "Louis Leterrier",
    "subtitle": "Bahasa Indonesia",
    "genre": "Action, Racing",
    "rating": 15,
    "price": 53000,
  },
  {
    "id": 1,
    "title": "John Wick: Chapter 4",
    "description":
      "John Wick mengungkap jalan untuk mengalahkan The High Table. Tapi sebelum dia bisa mendapatkan kebebasannya, Wick harus berhadapan dengan musuh baru dengan aliansi kuat di seluruh dunia dan kekuatan yang mengubah teman lama menjadi musuh.",
    "release_date": "2023-03-22",
    "poster": "https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
    "duration": 169,
    "movie_format": "2D",
    "director": " Chad Stahelski",
    "subtitle": "Bahasa Indonesia",
    "rating": 10,
    "price": 60000,
  },
  {
    "id": 2,
    "title": "The Super Mario Bros. Movie",
    "description":
      "Ketika sedang bekerja di bawah tanah untuk memperbaiki pipa air, Mario dan Luigi, yang merupakan tukang ledeng dari Brooklyn, tiba-tiba terhisap ke dalam pipa misterius dan masuk ke dunia yang sangat berbeda. Mereka berada di tempat yang ajaib dan aneh. Tapi sayangnya, mereka terpisah satu sama lain. Mario memulai petualangan besar untuk mencari dan menemukan Luigi.",
    "release_date": "2023-04-05",
    "poster": "https://image.tmdb.org/t/p/w500/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg",
    "duration": 92,
    "movie_format": "2D",
    "director": "Aaron Horvath, Michael Jelenic",
    "subtitle": "Bahasa Indonesia",
    "rating": 14,
    "price": 49000,
  },
  {
    "id": 7,
    "title": "Avatar: The Way of Water",
    "description": "Jake Sully tinggal bersama keluarga barunya di planet Pandora. Setelah ancaman kembali datang, Jake harus bekerja dengan Neytiri dan pasukan ras Na'vi untuk melindungi planet mereka.",
    "release_date": "2022-12-14",
    "poster": "https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    "duration": 192,
    "movie_format": "2D",
    "director": "James Cameron",
    "subtitle": "Bahasa Indonesia",
    "rating": 12,
    "price": 53000,
  },
  {
    "id": 5,
    "title": "Avatar: The Way of Water",
    "description": "Jake Sully tinggal bersama keluarga barunya di planet Pandora. Setelah ancaman kembali datang, Jake harus bekerja dengan Neytiri dan pasukan ras Na'vi untuk melindungi planet mereka.",
    "release_date": "2022-12-14",
    "poster": "https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    "duration": 120,
    "movie_format": "3D",
    "director": "Louis Leterrier",
    "subtitle": "Bahasa Indonesia",
    "rating": 12,
    "price": 53000,
  },
  {
    "id": 3,
    "title": "Extreme Job",
    "description":
      "Mengisahkan tentang sekelompok detektif narkotika muda yang terdiri dari 5 orang, yakni Kepala Pasukan Detektif Go (Ryu Seung-ryong), Detektif Jang (Lee Hanee), Detektif Ma (Jin Seon-kyu), Detektif Young-Ho (Lee Dong-hwi) dan Detektif Jae-Hoon (Gong Myung). Setelah gagal dalam misi terakhir mereka, Kapten Ko dan timnya ditawari satu kesempatan terakhir untuk menyelamatkan karier mereka. Mereka harus melakukan pengawasan rahasia terhadap geng narkoba internasional. Lokasi pengintaian mereka adalah restoran ayam. Segalanya tampak berhasil, tetapi Ko diberi tahu bahwa restoran tersebut akan segera gulung tikar. Tim mencoba untuk menjatuhkan organisasi kriminal itu dan mereka harus menyamar untuk melakukannya. Para detektif lalu mulai bekerja sebagai karyawan di sebuah restoran ayam. Mereka lalu berimprovisasi pada menu dengan membuat rendaman iga agar ayam lengket langsung menjadi hit, dan restoran ayam mereka justru menjadi terkenal dengan ayamnya yang lezat. Karena popularitas restoran yang tidak terduga, para detektif menemukan diri mereka dalam situasi yang tidak pernah mereka duga.",
    "release_date": "2019-01-23",
    "poster": "https://i0.wp.com/postyrandom.com/wp-content/uploads/2019/04/Poster-Extreme-Job-70x100-1-717x1024-e1555835988781.jpg?fit=600%2C857&ssl=1",
    "duration": 111,
    "movie_format": "2D",
    "director": "Lee Byeong-Hun",
    "subtitle": "Bahasa Indonesia, English",
    "rating": 15,
    "price": 55000,
  },
  {
    "id": 9,
    "title": "Guardians of the Galaxy Vol. 3",
    "description": "Peter Quill masih trauma karena kehilangan Gamora. Ia perlu mengumpulkan timnya untuk melindungi alam semesta dan salah satu anggota mereka. Jika mereka gagal, Guardian akan berakhir.",
    "release_date": "2023-05-03",
    "poster": "https://image.tmdb.org/t/p/w500/nAbpLidFdbbi3efFQKMPQJkaZ1r.jpg",
    "duration": 149,
    "movie_format": "2D",
    "director": " James Gunn",
    "subtitle": "Bahasa Indonesia",
    "rating": 12,
    "price": 41000,
  },
  {
    "id": 12,
    "title": "Ant-Man and the Wasp: Quantumania",
    "description":
      "Scott Lang dan Hope van Dyne adalah pasangan pahlawan super. Mereka pergi bersama orang tua Hope, Janet van Dyne dan Hank Pym, serta anak perempuan Scott, Cassie Lang, untuk menjelajahi Alam Kuantum. Di sana, mereka bertemu dengan makhluk-makhluk aneh dan memulai petualangan yang tak terduga. Petualangan ini akan menguji batas-batas mereka.",
    "release_date": "2023-02-15",
    "poster": "https://image.tmdb.org/t/p/w500/g0OWGM7HoIt866Lu7yKohYO31NU.jpg",
    "duration": 124,
    "movie_format": "2D",
    "director": "Peyton Reed",
    "subtitle": "Bahasa Indonesia",
    "rating": 12,
    "price": 51000,
  },
  {
    "id": 17,
    "title": "The Pope's Exorcist",
    "description":
      "Pastor Gabriele Amorth, yang memimpin tim pengusir setan di Vatikan, menginvestigasi kasus kekerasan roh jahat yang menghantui seorang anak laki-laki. Dalam penyelidikannya, ia secara tak terduga menemukan rahasia tua yang disembunyikan oleh Vatikan selama berabad-abad.",
    "release_date": "2023-04-05",
    "poster": "https://image.tmdb.org/t/p/w500/gNPqcv1tAifbN7PRNgqpzY8sEJZ.jpg",
    "duration": 103,
    "movie_format": "2D",
    "director": "Julius Averyr",
    "subtitle": "Bahasa Indonesia",
    "rating": 13,
    "price": 51000,
  },
  {
    "id": 19,
    "title": "To Catch a Killer",
    "description":
      "Baltimore. Malam tahun baru. Seorang petugas polisi yang berbakat tetapi bermasalah (Shailene Woodley) direkrut oleh kepala penyelidik FBI (Ben Mendelsohn) untuk membantu membuat profil dan melacak individu yang terganggu yang meneror kota.",
    "release_date": "2023-04-06",
    "poster": "https://image.tmdb.org/t/p/w500/mFp3l4lZg1NSEsyxKrdi0rNK8r1.jpg",
    "duration": 119,
    "movie_format": "2D",
    "director": "Damián Szifron",
    "subtitle": "Bahasa Indonesia",
    "rating": 15,
    "price": 47000,
  },
  {
    "id": 4,
    "title": "Transformers: Age of Extinction",
    "description": "Lima tahun setelah Chicago dihancurkan, manusia berbalik melawan robot. Namun seorang ayah tunggal dan penemu membangkitkan robot yang dapat menyelamatkan dunia.",
    "release_date": "2014-06-25",
    "poster": "https://image.tmdb.org/t/p/w500/jyzrfx2WaeY60kYZpPYepSjGz4S.jpg",
    "duration": 155,
    "movie_format": "2D",
    "director": "Michael Bay",
    "subtitle": "Bahasa Indonesia",
    "rating": 11,
    "price": 54000,
  },
  {
    "id": 27,
    "title": "Puss in Boots: The Last Wish",
    "description":
      "Puss in Boots menemukan fakta bahwa kecintaannya pada petualangan telah merenggut nyawanya: dia telah menghabiskan delapan dari sembilan nyawanya. Puss kini memulai petualangan epik untuk menemukan harapan terakhir untuk memulihkan sembilan nyawanya.",
    "release_date": "2022-12-07",
    "poster": "https://image.tmdb.org/t/p/w500/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    "duration": 102,
    "movie_format": "2D",
    "director": "Joel Crawford",
    "subtitle": "Bahasa Indonesia",
    "rating": 11,
    "price": 51000,
  },
  {
    "id": 22,
    "title": "Scream VI",
    "description": "Setelah pembunuhan terbaru oleh Ghostface, keempat orang yang selamat pergi dari Woodsboro dan memulai hidup baru.",
    "release_date": "2023-03-08",
    "poster": "https://image.tmdb.org/t/p/w500/wDWwtvkRRlgTiUr6TyLSMX8FCuZ.jpg",
    "duration": 122,
    "movie_format": "2D",
    "director": "Tyler Gillett, Matt Bettinelli-Olpin",
    "subtitle": "Bahasa Indonesia",
    "rating": 12,
    "price": 36000,
  },
  {
    "id": 14,
    "title": "Black Adam",
    "description":
      "Hampir 5.000 tahun setelah dia dianugerahi kekuatan maha kuasa para dewa Mesirâ€”dan dipenjara dengan cepatâ€”Black Adam dibebaskan dari makam duniawinya, siap untuk melepaskan bentuk keadilannya yang unik di dunia modern.",
    "release_date": "2022-10-19",
    "poster": "https://image.tmdb.org/t/p/w500/A5imhXiFF3AL9RRA4FBzNDFmfgW.jpg",
    "duration": 125,
    "movie_format": "2D",
    "director": "Jaume Collet-Serra",
    "subtitle": "Bahasa Indonesia",
    "rating": 10,
    "price": 42000,
  },
  {
    "id": 15,
    "title": "Dungeons & Dragons: Honor Among Thieves",
    "description": "Seorang pencuri menawan dan sekelompok petualang yang unik melakukan pencurian besar-besaran untuk mencuri relik yang hilang. Namun, segalanya menjadi kacau ketika mereka berjumpa dengan orang yang salah.",
    "release_date": "2023-03-23",
    "poster": "https://image.tmdb.org/t/p/w500/A7AoNT06aRAc4SV89Dwxj3EYAgC.jpg",
    "duration": 134,
    "movie_format": "2D",
    "director": "John Francis Daley, Jonathan Goldstein",
    "subtitle": "Bahasa Indonesia",
    "rating": 12,
    "price": 38000,
  },
  {
    "id": 16,
    "title": "Peter Pan & Wendy",
    "description":
      "Wendy Darling adalah seorang gadis kecil yang takut pergi dari rumah masa kecilnya. Suatu hari, dia bertemu dengan Peter Pan, seorang anak laki-laki yang tidak mau tumbuh dewasa. Mereka bersama saudara-saudaranya dan peri kecil bernama Tinker Bell pergi ke dunia ajaib yang disebut Neverland. Di sana, mereka menghadapi Kapten Hook, seorang bajak laut jahat, dan mengalami petualangan seru yang akan mengubah hidup Wendy selamanya.",
    "release_date": "2023-04-20",
    "poster": "https://image.tmdb.org/t/p/w500/9NXAlFEE7WDssbXSMgdacsUD58Y.jpg",
    "duration": 109,
    "movie_format": "2D",
    "director": "David Lowery",
    "subtitle": "Bahasa Indonesia",
    "rating": 13,
    "price": 35000,
  },
  {
    "id": 36,
    "title": "SPIDER-MAN: ACROSS THE SPIDER-VERSE",
    "description":
      "Miles Morales melontarkan diri melintasi Multiverse, di mana dia bertemu dengan tim Spider-People yang bertugas melindungi keberadaannya. Saat para pahlawan bentrok tentang cara menangani ancaman baru, Miles harus mendefinisikan kembali arti dari menjadi seorang pahlawan.",
    "release_date": "2023-06-10",
    "poster": "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    "movie_format": "2D",
    "duration": 140,
    "director": "Justin K. Thompson, Kemp Powers",
    "genre": "animation",
    "subtitle": "Bahasa Indonesia",
    "rating": 13,
    "price": 45000,
  },
  {
    "id": 37,
    "title": "FS: RUROUNI KENSHIN",
    "description":
      "Setelah hampir 30 tahun serial mengudara, anime TV baru Rurouni Kenshin akan segera hadir. Pemutaran Spesial Rurouni Kenshin terdiri dari 4 episode pertama dari anime TV baru yang tayang perdana pada 6 Juli 2023. Selama era kekerasan yang dikenal sebagai Bakumatsu, seorang pembunuh Ishin yang hanya dikenal sebagai Hitokiri Battousai, dengan keterampilan dan kebrutalannya menjadi legendaris di zaman Pemulihan yang ia bantu bangun. Namun, saat pertempuran hampir berakhir, dia menghilang tanpa jejak, hanya untuk muncul kembali sebelas tahun kemudian sebagai pendekar pengembara, Himura Kenshin. Sekarang tinggal di dojo kenjutsu yang dikelola oleh seorang wanita pemarah bernama Kamiya Kaoru, dan dikelilingi oleh teman-teman baru seperti petarung jalanan Sagara Sanosuke, putra mantan samurai Myoujin Yahiko, dan dokter cerdik Takani Megumi, dia berusaha untuk melaksanakan sumpahnya untuk melindungi yang lemah tanpa membunuh untuk menebus nyawa yang diambilnya. Namun, tidak lama kemudian, sebelum sumpah ini diuji, dan bayang-bayang masa lalunya kembali menghantuinya dan semua orang yang dia sayangi.",
    "release_date": "2023-06-10",
    "poster": "https://asset.tix.id/wp-content/uploads/2023/06/d87fc8d2-5bfd-41d7-ba68-b73abbac52b9.jpeg",
    "movie_format": "2D",
    "duration": 80,
    "director": "Hideyo Yamamoto",
    "genre": "animation",
    "subtitle": "Bahasa Indonesia, English",
    "rating": 13,
    "price": 35000,
  },
  {
    "id": 18,
    "title": "Spider-Man: No Way Home",
    "description":
      "Peter Parker menghadapi masalah besar. Hal ini terjadi setelah identitasnya sebagai Spiderman terungkap. Dengan kepergian Tony Stark, Peter Parker pun harus meminta bantuan Doctor Strange agar semua orang bisa melupakan identitasnya sebagai manusia laba-laba.",
    "release_date": "2021-12-15",
    "poster": "https://image.tmdb.org/t/p/w500/uJYYizSuA9Y3DCs0qS4qWvHfZg4.jpg",
    "duration": 148,
    "movie_format": "2D",
    "director": "Jon Watts",
    "subtitle": "Bahasa Indonesia",
    "rating": 15,
    "price": 56000,
  },
  {
    "id": 29,
    "title": "Black Panther: Wakanda Forever",
    "description": "Rakyat Wakanda kali ini akan berjuang untuk melindungi negerinya dari campur tangan kekuatan dunia setelah kematian sang Raja T'Challa.",
    "release_date": "2022-11-09",
    "poster": "https://image.tmdb.org/t/p/w500/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
    "duration": 135,
    "movie_format": "2D",
    "director": "Ryan Coogler",
    "subtitle": "Bahasa Indonesia",
    "rating": 13,
    "price": 39000,
  },
  {
    "id": 6,
    "title": "Transformers: The Last Knight",
    "description":
      "Di tengah ketidakhadiran Optimus Prime, umat manusia berperang melawanTransformers untuk mempertahankan eksistensinya. Cade Yeager membentuk kerjasama dengan Bumblebee, seorang bangsawan Inggris dan seorang professor dari Oxford untuk mempelajari mengapa Transformers selalu kembali ke planet bumi.",
    "release_date": "2017-06-16",
    "poster": "https://image.tmdb.org/t/p/w500/s5HQf2Gb3lIO2cRcFwNL9sn1o1o.jpg",
    "duration": 149,
    "movie_format": "2D",
    "director": " Michael Bay",
    "subtitle": "Bahasa Indonesia",
    "rating": 12,
    "price": 52000,
  },
  {
    "id": 33,
    "title": "Renfield",
    "description":
      "Setelah bertahun-tahun sebagai hamba Dracula yang merasa jenuh dan lelah, Renfield menemukan harapan baru dalam hidupnya. Dia jatuh cinta pada Rebecca Quincy, seorang polisi lalu lintas yang energik dan sering marah. Kesempatan ini bisa menjadi penebusan baginya.",
    "release_date": "2023-04-07",
    "poster": "https://image.tmdb.org/t/p/w500/2OaprROMZZeiWsydjGUIkXrv2Z3.jpg",
    "duration": 93,
    "movie_format": "2D",
    "director": "Chris McKay",
    "subtitle": "Bahasa Indonesia",
    "rating": 14,
    "price": 51000,
  },
  {
    "id": 32,
    "title": "Cocaine Bear",
    "description": "Sekelompok polisi, penjahat, turis, dan remaja eksentrik berkumpul di hutan Georgia tempat beruang hitam besar mengamuk setelah menelan kokain secara tidak sengaja.",
    "release_date": "2023-02-22",
    "poster": "https://image.tmdb.org/t/p/w500/gOnmaxHo0412UVr1QM5Nekv1xPi.jpg",
    "duration": 95,
    "movie_format": "2D",
    "director": "Elizabeth Banks",
    "subtitle": "Bahasa Indonesia",
    "rating": 12,
    "price": 53000,
  },
  {
    "id": 40,
    "title": "Prey",
    "description": "Di Comanche Nation pada tahun 1717, seorang pejuang yang ganas dan sangat terampil bernama Naru mengetahui bahwa mangsa yang dia intai adalah alien yang sangat berkembang dengan persenjataan berteknologi maju.",
    "release_date": "2022-08-02",
    "poster": "https://image.tmdb.org/t/p/w500/ujr5pztc1oitbe7ViMUOilFaJ7s.jpg",
    "duration": 100,
    "movie_format": "2D",
    "director": "Dan Trachtenberg",
    "subtitle": "Bahasa Indonesia",
    "rating": 10,
    "price": 42000,
  },
  {
    "id": 8,
    "title": "Fall",
    "description":
      "Untuk sahabat Becky dan Hunter, hidup adalah tentang menaklukkan ketakutan dan mendorong batas. Tetapi setelah mereka mendaki 2.000 kaki ke puncak menara radio terpencil yang ditinggalkan, mereka menemukan diri mereka terdampar tanpa jalan turun. Sekarang keterampilan panjat ahli Becky dan Hunter akan diuji saat mereka mati-matian berjuang untuk bertahan hidup dari unsur-unsur, kurangnya persediaan, dan ketinggian yang menyebabkan vertigo.",
    "release_date": "2022-08-11",
    "poster": "https://image.tmdb.org/t/p/w500/v28T5F1IygM8vXWZIycfNEm3xcL.jpg",
    "duration": 107,
    "movie_format": "2D",
    "director": "Scott Mann",
    "subtitle": "Bahasa Indonesia",
    "rating": 11,
    "price": 39000,
  },
  {
    "id": 13,
    "title": "Avatar",
    "description": "Pada abad ke-22, seorang Marinir lumpuh dikirim ke Pandora bulan pada misi yang unik, tetapi menjadi terpecah antara mengikuti perintah dan melindungi peradaban alien.",
    "release_date": "2009-12-15",
    "poster": "https://image.tmdb.org/t/p/w500/kyeqWdyUXW608qlYkRqosgbbJyK.jpg",
    "duration": 162,
    "movie_format": "2D",
    "director": " James Cameron",
    "subtitle": "Bahasa Indonesia",
    "rating": 13,
    "price": 37000,
  },
  {
    "id": 38,
    "title": "Split",
    "description":
      "Ketika ketiga gadis remaja sedang menunggu ayah mereka di dalam mobil, seorang pria misterius menculik dan membawa mereka ke dalam sebuah bunker. Sang penculik yang bernama Kevin (James McAvoy) adalah seorang pria dengan gangguan jiwa yang membuatnya memiliki 23 kepribadian yang berbeda, yang diantaranya adalah seorang wanita dan anak berumur 9 tahun yang bernama Hedwig.  Sebagai salah satu gadis yang diculik, Casey berusaha meloloskan diri dengan meyakinkan salah satu kepribadian Kevin untuk melepaskan mereka. Akan tetapi hal tersebut tidaklah mudah, terlebih setelah Hedwig memperingatkan mereka akan the Beast yang merupakan kepribadian Kevin yang paling berbahaya.",
    "release_date": "2017-01-19",
    "poster": "https://image.tmdb.org/t/p/w500/lli31lYTFpvxVBeFHWoe5PMfW5s.jpg",
    "duration": 117,
    "movie_format": "2D",
    "director": " M. Night Shyamalan",
    "subtitle": "Bahasa Indonesia",
    "rating": 10,
    "price": 45000,
  },
  {
    "id": 31,
    "title": "Top Gun: Maverick",
    "description":
      'Setelah lebih dari tiga puluh tahun mengabdi sebagai salah satu penerbang top Angkatan Laut, dan menghindari kenaikan pangkat yang akan menjatuhkannya, Pete "Maverick" Mitchell mendapati dirinya melatih satu detasemen lulusan TOP GUN untuk misi khusus yang tidak ada kehidupan. pilot pernah melihat.',
    "release_date": "2022-05-24",
    "poster": "https://image.tmdb.org/t/p/w500/jeGvNOVMs5QIU1VaoGvnd3gSv0G.jpg",
    "duration": 130,
    "movie_format": "2D",
    "director": "Joseph Kosinski",
    "subtitle": "Bahasa Indonesia",
    "rating": 14,
    "price": 57000,
  },
  {
    "id": 24,
    "title": "Thor: Love and Thunder",
    "description":
      '"Thor: Love and Thunder"menceritakan Thor (Chris Hemsworth) dalam sebuah perjalanan yang belum pernah ia jalani â€“ pencariankedamaian batin. Namun, masa pensiunnya terganggu oleh seorang pembunuh galaksi yang dikenal sebagai Gorr sang Dewa Jagal (Christian Bale), yang ingin memusnahkan para dewa. Untuk mengatasi ancaman, Thor meminta bantuan Raja Valkyrie (Tessa Thompson), Korg (Taika Waititi), dan mantan kekasihnya Jane Foster (Natalie Portman), yang secara mengejutkan dan misterius berhasil menggunakan palu ajaibnya, Mjolnir, sebagai Mighty Thor. Bersama, mereka memulai petualangan kosmik yang mendebarkan untuk mengungkap misteri pembalasan Dewa Jagal dan menghentikannya sebelum terlambat.',
    "release_date": "2022-07-06",
    "poster": "https://image.tmdb.org/t/p/w500/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",
    "duration": 119,
    "movie_format": "2D",
    "director": "Taika Waititi",
    "subtitle": "Bahasa Indonesia",
    "rating": 12,
    "price": 35000,
  },
  {
    "id": 11,
    "title": "Sonic the Hedgehog 2",
    "description":
      "Alur cerita film Sonic the Hedgehog 2 bermula ketika Sonic menetap di Green Hills. Ia memutuskan menetap di sana agar bisa merasakan lebih banyak kebebasan. Ditambah lagi, Tom dan Maddie setuju untuk meninggalakannya di rumah ketika mereka pergi untuk berlibur. Namun sayangnya, tidak lama setelah mereka pergi Dr. Robotnik sang musuh bubuyutan si landak biru itu kembali ke bumi. Kali ini Dr. Robotnik datang dengan pasukan baru, Knuckles. Tujuan mereka datang kembali adalah untuk mencari Master Emerald yang memiliki kekuatan super. Kekuatan super itu bisa membangun dan menghancurkan peradaban di bumi. Atas hal ini, Sonic pun mencari strategi agar bisa menggagalkan rencara Dr. Robotnik. Strategi yang dilakukan oleh Sonic ialah bekerjasama dengan sahabatnya, Tails. Kemudian bersama dengan Tails, Sonic memulai perjalanan untuk menemukan Master Emerald. Semua itu dilakukan dengan cepat, sebelum Master Emerald jatuh ke tangan yang salah.",
    "release_date": "2022-04-08",
    "poster": "https://image.tmdb.org/t/p/w500/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg",
    "duration": 135,
    "movie_format": "2D",
    "director": " Jeff Fowler",
    "subtitle": "Bahasa Indonesia",
    "rating": 12,
    "price": 45000,
  },
  {
    "id": 21,
    "title": "Avengers: Infinity War",
    "description":
      "Karena Avengers dan sekutunya terus melindungi dunia dari ancaman yang terlalu besar untuk ditangani oleh seorang pahlawan, bahaya baru telah muncul dari bayangan kosmik: Thanos. Seorang lalim penghujatan intergalaksi, tujuannya adalah untuk mengumpulkan semua enam Batu Infinity, artefak kekuatan yang tak terbayangkan, dan menggunakannya untuk menimbulkan kehendak memutar pada semua realitas. Segala sesuatu yang telah diperjuangkan oleh Avengers telah berkembang hingga saat ini - nasib Bumi dan keberadaannya sendiri tidak pernah lebih pasti.",
    "release_date": "2018-04-25",
    "poster": "https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
    "duration": 159,
    "movie_format": "2D",
    "director": " Anthony Russo, Joe Russo",
    "subtitle": "Bahasa Indonesia",
    "rating": 10,
    "price": 46000,
  },
  {
    "id": 28,
    "title": "The Whale",
    "description": "Seorang guru bahasa Inggris yang tertutup dan gemuk mencoba untuk berhubungan kembali dengan putri remajanya yang terasing.",
    "release_date": "2022-12-09",
    "poster": "https://image.tmdb.org/t/p/w500/jQ0gylJMxWSL490sy0RrPj1Lj7e.jpg",
    "duration": 117,
    "movie_format": "2D",
    "director": " Darren Aronofsky",
    "subtitle": "Bahasa Indonesia",
    "rating": 15,
    "price": 55000,
  },
  {
    "id": 26,
    "title": "The Batman",
    "description": "Ketika seorang pembunuh berantai sadis mulai membunuh tokoh-tokoh politik penting di Gotham, Batman terpaksa menyelidiki korupsi tersembunyi di kota itu dan mempertanyakan keterlibatan keluarganya.",
    "release_date": "2022-03-01",
    "poster": "https://image.tmdb.org/t/p/w500/seyWFgGInaLqW7nOZvu0ZC95rtx.jpg",
    "duration": 176,
    "movie_format": "2D",
    "director": " Matt Reeves",
    "subtitle": "Bahasa Indonesia",
    "rating": 13,
    "price": 53000,
  },
  {
    "id": 25,
    "title": "Smile",
    "description":
      "Setelah menyaksikan kejadian aneh dan traumatis yang melibatkan seorang pasien, Dr. Rose Cotter mulai mengalami kejadian menakutkan yang tidak dapat dia jelaskan. Saat teror luar biasa mulai mengambil alih hidupnya, Rose harus menghadapi masa lalunya yang bermasalah untuk bertahan hidup dan melarikan diri dari kenyataan barunya yang mengerikan.",
    "release_date": "2022-09-23",
    "poster": "https://image.tmdb.org/t/p/w500/67Myda9zANAnlS54rRjQF4dHNNG.jpg",
    "duration": 115,
    "movie_format": "2D",
    "director": "Parker Finn",
    "subtitle": "Bahasa Indonesia",
    "rating": 11,
    "price": 38000,
  },
  {
    "id": 30,
    "title": "Encanto",
    "description":
      "menceritakan tentang keluarga Madrigals, sebuah keluarga yang tinggal di rumah ajaib dan masing-masing anggota keluarga memiliki keajaibannya tersendiri. Pada jaman dahulu kala, Abuela bersama suami dan anak-anaknya melarikan diri dari kerusuhan di desa.",
    "release_date": "2021-10-13",
    "poster": "https://image.tmdb.org/t/p/w500/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg",
    "duration": 109,
    "movie_format": "2D",
    "director": "Byron Howard, Jared Bush        ",
    "subtitle": "Bahasa Indonesia",
    "rating": 12,
    "price": 44000,
  },
];
